### ISSUE TITLE
`Bug` Test run name link navigates to blank page

### ISSUE THREAD

**Issue by A-Harby** [Mahmoud-Emad/test-tracker#10]
After you finishes test run of test suite test run name link navigate you to a blank page.

![image](https://user-images.githubusercontent.com/109473873/194118853-85652894-3fbf-4edb-ad7e-4777beac738d.png)

![image](https://user-images.githubusercontent.com/109473873/194119217-452a9e5c-c21b-40aa-bbb8-5422048a2c00.png)

**Comment by Mahmoud-Emad** [comment]
Fixed!
